### ISSUE TITLE
[BUG] Can not decrypt JSON array over JWE entire payload mode

### ISSUE THREAD

**Issue by migbtn** [Mastercard/client-encryption-java#53]
#### Bug Report Checklist

- [x] Have you provided a code sample to reproduce the issue?
- [x] Have you tested with the latest release to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

**Description**
I can't decrypt simple JSON array or JSON array consisted of objects over the JWE entire payload mode (I had encrypted it before decryption process in my own). The decryption process throws an exception: `com.jayway.jsonpath.PathNotFoundException`.
I mean arrays like below:
```
["abcd", "efgh"]
```
or
```
[
  {
    "field": "abcd"
  },
  {
    "field": "efgh"
  }
]
```

The exception stacktrace:
```
com.mastercard.developer.encryption.EncryptionException: Payload decryption failed!

	at com.mastercard.developer.encryption.JweEncryption.decryptPayload(JweEncryption.java:58)
	at com.example.EncryptionTestUtil.decrypt(EncryptionTestUtil.java:31)
	at com.example.EncryptionTestUtil.test1(EncryptionTestUtil.java:56)<31 internal lines>
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) <9 internal lines>
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) <23 internal lines>

Caused by: com.jayway.jsonpath.PathNotFoundException: Expected to find an object with property ['encryptedValue'] in path $ but found 'java.util.ArrayList'. This is not a json object according to the JsonProvider: 'com.jayway.jsonpath.spi.json.JacksonJsonProvider'.
	at com.jayway.jsonpath.internal.path.PropertyPathToken.evaluate(PropertyPathToken.java:71)
	at com.jayway.jsonpath.internal.path.RootPathToken.evaluate(RootPathToken.java:62)
	at com.jayway.jsonpath.internal.path.CompiledPath.evaluate(CompiledPath.java:99)
	at com.jayway.jsonpath.JsonPath.delete(JsonPath.java:258)
	at com.jayway.jsonpath.internal.JsonContext.delete(JsonContext.java:160)
	at com.jayway.jsonpath.internal.JsonContext.delete(JsonContext.java:155)
	at com.mastercard.developer.encryption.JweEncryption.decryptPayloadPath(JweEncryption.java:118)
	at com.mastercard.developer.encryption.JweEncryption.decryptPayload(JweEncryption.java:52)
	... 67 more
```

**To Reproduce**
Code snippet:
```java
 public static String decrypt(String value) throws Exception {
    var config =
        JweConfigBuilder.aJweEncryptionConfig()
            .withDecryptionPath("$.encryptedValue", "$")
            .withDecryptionKey(CertificateTestFactory.createPrivateKey())
            .build();

    return JweEncryption.decryptPayload(value, config);
  }

  @Test
  void test1() throws Exception {
    String objectArray = "[{\"field\":\"abcd\"}, {\"field\":\"efgh\"}]";
    String stringArray = "[\"abcd\", \"efgh\"]";

    JweConfig jweConfig = prepareConfigurationForEntireResponseEncryption(CertificateTestFactory.createEncryptionCertificate());

    String encryptedStringArray = JweEncryption.encryptPayload(stringArray, jweConfig);
    System.out.println("encryptedStringArray: " + encryptedStringArray);
    System.out.println("decryptedStringArray: " + decrypt(encryptedStringArray));


    String encryptedObjectArray = JweEncryption.encryptPayload(objectArray, jweConfig);
    System.out.println("encryptedObjectArray: " + encryptedObjectArray);
    System.out.println("decryptedObjectArray: " + decrypt(encryptedObjectArray));
  }

  private JweConfig prepareConfigurationForEntireResponseEncryption(Certificate certificate)
          throws EncryptionException {
    return JweConfigBuilder.aJweEncryptionConfig()
            .withEncryptionCertificate(certificate)
            .withEncryptionPath("$", "$")
            .withEncryptedValueFieldName("encryptedValue")
            .build();
  }
```

**Expected behavior**
Getting a value encrypted before.

**Additional context**
The configuration is prepared in compliance with https://github.com/Mastercard/client-encryption-java#encrypting-entire-payloads-jwe

**Comment by jaaufauvre** [comment]
Array encryption/decryption shouldn't be a problem:
- [testEncryptPayload_ShouldEncryptRootArrays](https://github.com/Mastercard/client-encryption-java/blob/main/src/test/java/com/mastercard/developer/encryption/JweEncryptionWithDefaultJsonEngineTest.java#L15-L34)
- [testDecryptPayload_ShouldDecryptRootArrays](https://github.com/Mastercard/client-encryption-java/blob/main/src/test/java/com/mastercard/developer/encryption/JweEncryptionWithDefaultJsonEngineTest.java#L55-L70)

Also, the code you provided works. Here are the logs I'm getting:
```
encryptedStringArray: {
  "encryptedValue": "ewogICJraWQiOiAiNzYxYjAwM2MxZWFkZTNhNTQ5MGU1MDAwZDM3ODg3YmFhNWU2ZWMwZTIyNmMwNzcwNmU1OTk0NTFmYzAzMmE3OSIsCiAgImN0eSI6ICJhcHBsaWNhdGlvblwvanNvbiIsCiAgImVuYyI6ICJBMjU2R0NNIiwKICAiYWxnIjogIlJTQS1PQUVQLTI1NiIKfQ.QVqaWxNmPlWPMmKJkUu02gwlOKLZWv4i8mNG1ehf1Kn3cHgKyOahgHiNPeIloudTHKY6x5ey4G1hbpnhp9D2rROTE0MUA_zNPh5gFqBm7JOOsBedtywr4noDGZhHfs_mmoQsXZAbFdkQ1eF6MEXesyPtVz02AzImkWofP-4JIpT6uIwHa5r6fC-huo0ZgmJV4jmdhqKJPGIsf6nVgOvKSrkUrw5CF1FTcHc-WNS7ZqJC9zr8x9zafF_-8Zf-E7I4g28T801Nn4JFWIktxMAkFypld5tseNeMptQ0oNYzi0yVV4zp7VxOyN_30n6fwNKxEZDKZM32hjYk30MZjq-Zbw.FnFjPvF5qVDklOPDd-PyyA.OOXUFe7ql_Lf-Iu4BQKHBOg0_w.bBiYb7BfFCUrPKrIunankQ"
}
decryptedStringArray: [
  "abcd",
  "efgh"
]
encryptedObjectArray: {
  "encryptedValue": "ewogICJraWQiOiAiNzYxYjAwM2MxZWFkZTNhNTQ5MGU1MDAwZDM3ODg3YmFhNWU2ZWMwZTIyNmMwNzcwNmU1OTk0NTFmYzAzMmE3OSIsCiAgImN0eSI6ICJhcHBsaWNhdGlvblwvanNvbiIsCiAgImVuYyI6ICJBMjU2R0NNIiwKICAiYWxnIjogIlJTQS1PQUVQLTI1NiIKfQ.P1iqWA5ssAXMDwe9iau2KSWnVxWAvVTdmqWwceAwGTfGyQiZfheq_zF1dSRlM7Miux4VG41-65yWS9FZyoBLYPCGlkqcRDboSCRuZM1ZGpucN0FkYrNwS9AhtzJ_Ur3EHuVedO9e0UwlO4TM66P5m9Yh2Go4g-JkwqAz7EudSRpbyInPCrOJZKwu1FMGoXSR4cMokyIaE2lbuNSHKIoRvdmoLouU06T_PhLmh6rB-4erimsvNW5BTj3xuIYfxYbQq8evMZIRsFc7i2t3fAQmwBR6m2ylnQ-oBFzh5oe9MHSewsy1KsSqMoNBq4cZ6eBZazxJ2jsD2Mtj8qaSPlvezA.76gph8QqblNWASUW5rXNAQ.J0KsEO7ioWOgTGwkaK-Y4-8XAu0pk0hZNOg43wHbTTwe6QWDw1sOF1-x-2hs8GO-0Qu-6UM.tf7avdebeDfcXN_CAta_zg"
}
decryptedObjectArray: [
  {
    "field": "abcd"
  },
  {
    "field": "efgh"
  }
]
```
